### PR TITLE
reactor: phone Migration to username

### LINKED ISSUE #338: [功能] - 增加普通用户名和密码登录
## what

现在是基于手机号作为帐号的

不过我们其实用不到手机号 

等到后面有付费功能的时候在采用手机号的方式登录 （手机号需要走验证码）

让用户自己随便用个帐号来注册就好了

## how

之前表里面存的是 phone

换成普通的帐号需要注册格式的处理

需要思考兼容性上的问题

原有的手机号验证逻辑需要保留封装到组件中

（后续用的到）

### PR DESCRIPTION
**Pull request by baboon-king**
close #338 

- [x] client
  - [x] remove phone formItem on SignIn/SignUp page
  - [x] add new username formItem to SignIn/SignUp page
  - [x] name modify to nickname on SignUp page
  - [x] sync the latest variable name to the reference
  - [x] other

- [x] api
  - [x] signIn
  - [x] signUp
  - [x] unit-test

- [x] database
  - [x] cancel the unique of phone
  - [x] add username field to enable unique
  - [x] modify the name field to nickname

### CODE REVIEW

**Comment by hildxd** [comment]
写完了艾特我

**Comment by hildxd** [comment]
要帮忙不

**Comment by baboon-king** [comment]
> 写完了艾特我

东哥，快了快了！

**Comment by baboon-king** [comment]
> 写完了艾特我

@hildxd 东哥
看起来，这个 PR 已经准备好 Review.

**Comment by cuixiaorui** [comment]
感谢🙏🏻
用户系统已经迁移到 logto

**Pull request closed without merging**
