### PR TITLE
feat: add shortcut key unit test

### PR DESCRIPTION
**Pull request by vampirewy**

### CODE REVIEW

**Comment by zclsx** [comment]
> _ No description provided. _

希望能针对本次pr增加一下详细的描述，这样方便review代码，感谢！

**Comment by vampirewy** [comment]
> > _ No description provided. _
> 
> 希望能针对本次pr增加一下详细的描述，这样方便review代码，感谢！

This is a unit test file for the shortcutKey.ts file.

The file describes how to expect the content of the useShortcutKeyMode function. It consists of three main parts for your reference:  

1. Initialize default shortcut key and store them in local storage when the setShortcutKeys function is called

2. Save the custom shortcut key in local storage when the client presses the Enter key again. Two situations are involved: saving a single key and saving combination keys.

3. Show the custom shortcut key tips. 

The above comprises the three main sections of the file

if there are  any problems, please contact me, thank you

**Comment by fengstats** [comment]
@vampirewy Sorry, there was a small refactoring in the user-defined shortcut keys part, so there are some conflicts in the code that were not reviewed in time. 

Can you submit a new PR based on the current code, and I will review it as soon as possible? thanks~ 😊

**Comment by vampirewy** [comment]
> @vampirewy Sorry, there was a small refactoring in the user-defined shortcut keys part, so there are some conflicts in the code that were not reviewed in time.
> 
> Can you submit a new PR based on the current code, and I will review it as soon as possible, thanks! 😊

Thanks for your reply~ @fengstats 

I‘m opening a new PR which is PR number  #357

**Comment by fengstats** [comment]
> > @vampirewy Sorry, there was a small refactoring in the user-defined shortcut keys part, so there are some conflicts in the code that were not reviewed in time.
> > Can you submit a new PR based on the current code, and I will review it as soon as possible, thanks! 😊
> 
> Thanks for your reply~ @fengstats
> 
> I‘m opening a new PR which is PR number #357

received~

**Pull request closed without merging**
